// Generated by CoffeeScript 1.6.2
(function() {
  require.config({
    deps: ["main"],
    baseUrl: "/",
    paths: {
      jquery: "vendor/jquery",
      lodash: "vendor/lodash",
      backbone: "vendor/backbone",
      jade: "vendor/jade"
    },
    shim: {
      lodash: {
        exports: "_"
      },
      backbone: {
        deps: ["lodash", "jquery"],
        exports: "Backbone"
      }
    }
  });

}).call(this);
